[project]
name = "kegger"
version = "0.1.5"
description = "Interact with KEGG API"
readme = "README.md"
authors = [
    { name = "csaltikov", email = "saltikov@ucsc.edu" }
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
requires-python = ">=3.13"
keywords = ["bioinformatics", "genomics", "KEGG", "metabolism", "api-wrapper", "pandas", "microbiology"]

[project.urls]
Homepage = "https://github.com/csaltikov/kegger"
Repository = "https://github.com/csaltikov/kegger"
Issues = "https://github.com/csaltikov/kegger/issues"

dependencies = [
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "requests-cache>=1.2.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.1",
    "mkdocstrings[python]>=1.0.2",
    "pandas-stubs>=2.3.3.260113",
    "types-pytz>=2025.2.0.20251108",
]
